// Express
import express from "express";
import http from "http";
import bodyParser from "body-parser";
import path from "path";

// Swagger
import swaggerUi from "swagger-ui-express";
import yaml from "yamljs";

// Logging
import Logger from "./Logger";

// Properties
import properties from "../properties.js";

// Security
import cors from "cors";
import helmet from "helmet";

// Controllers
import SecurityController from "../controllers/SecurityController";

// Start Import Controllers

// Database
import Database_Sms_db from "./Database_Sms_db.js";

// Controllers
import DepartmentController from "../controllers/Sms_db/DepartmentController";
import DesignationController from "../controllers/Sms_db/DesignationController";
import StaffController from "../controllers/Sms_db/StaffController";
import UserController from "../controllers/Sms_db/UserController";
import Academic_yearController from "../controllers/Sms_db/Academic_yearController";
import Blood_groupController from "../controllers/Sms_db/Blood_groupController";
import ClasssesController from "../controllers/Sms_db/ClasssesController";
import GenderController from "../controllers/Sms_db/GenderController";
import ReligionController from "../controllers/Sms_db/ReligionController";
import RolesController from "../controllers/Sms_db/RolesController";
import SchoolController from "../controllers/Sms_db/SchoolController";
import SectionController from "../controllers/Sms_db/SectionController";
import StudentController from "../controllers/Sms_db/StudentController";

// End Import Controllers


class Server {
  constructor() {
    this.app = express();
  }

  /**
   * Start the server
   * @returns {Promise<void>}
   */
  async init() {
    Logger.info(
      "\r\n\r\n-----------------------------------\r\n\r\nStarting sms \r\nGenerated by\r\n\r\n   _____ _          __  __      _     _           \r\n  / ____| |        / _|/ _|    | |   | |          \r\n | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __ \r\n  \\___ \\| |/ / _` |  _|  _/ _ \\| |/ _` |/ _ \\ '__|\r\n  ____) |   < (_| | | | || (_) | | (_| |  __/ |   \r\n |_____/|_|\\_\\__,_|_| |_| \\___/|_|\\__,_|\\___|_|   \r\n\r\nFor more documentation please visit https://skaffolder.com/#/documentation\r\n\r\n-----------------------------------\r\n\r\n"
    );

    // Start Init Database
		Database_Sms_db.init();
 // End Init Database

    // Add parser
    this.app.use(bodyParser.json());
    this.app.use(bodyParser.urlencoded({ extended: true }));
    this.app.use(Logger.expressMiddleware);

    // Securitiy
    this.app.use(helmet());
    this.app.use(cors());

    // Swagger
    const swaggerDocument = yaml.load("./swagger.yaml");
    this.app.use(
      "/api/docs",
      swaggerUi.serve,
      swaggerUi.setup(swaggerDocument)
    );

    // Redirect frontend
    this.app.use("*", (req, res, next) => {
      if (req.originalUrl) {
        let url = req.originalUrl;
        if (!url.startsWith("/api/") && url.indexOf(".") == -1) {
          res
            .status(200)
            .sendFile(
              path.resolve(
                __dirname +
                  "//..//" +
                  properties.publicPath.replace(/\//g, "//") +
                  "//index.html"
              )
            );
        } else {
          next();
        }
      } else {
        next();
      }
    });
    
    // Start App Server
    const server = http.Server(this.app);
    this.app.use(express.static(properties.publicPath));

    await server.listen(properties.port);
    Logger.info("Server started on port " + properties.port);
    Logger.info(
      "Swagger docs at http://localhost:" + properties.port + "/api/docs"
    );

    // Import controllers
    const router = express.Router();
    SecurityController.init(router);

    // Start Init Controllers
		DepartmentController.init(router);
		DesignationController.init(router);
		StaffController.init(router);
		UserController.init(router);
		Academic_yearController.init(router);
		Blood_groupController.init(router);
		ClasssesController.init(router);
		GenderController.init(router);
		ReligionController.init(router);
		RolesController.init(router);
		SchoolController.init(router);
		SectionController.init(router);
		StudentController.init(router);
		 // End Init Controllers

    this.app.use("/", router);
  }
}

export default new Server();
