
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// DEPARTMENT
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const FINDBYSCHOOL_ID_DEPARTMENT_SUCCESS = "FINDBYSCHOOL_ID_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const LIST_DEPARTMENT_SUCCESS = "LIST_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";

// DESIGNATION
export const CREATE_DESIGNATION_SUCCESS = "CREATE_DESIGNATION_SUCCESS";
export const DELETE_DESIGNATION_SUCCESS = "DELETE_DESIGNATION_SUCCESS";
export const FINDBYSCHOOL_ID_DESIGNATION_SUCCESS = "FINDBYSCHOOL_ID_DESIGNATION_SUCCESS";
export const GET_DESIGNATION_SUCCESS = "GET_DESIGNATION_SUCCESS";
export const LIST_DESIGNATION_SUCCESS = "LIST_DESIGNATION_SUCCESS";
export const UPDATE_DESIGNATION_SUCCESS = "UPDATE_DESIGNATION_SUCCESS";

// STAFF
export const CREATE_STAFF_SUCCESS = "CREATE_STAFF_SUCCESS";
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const FINDBYDEPARTMENT_ID_STAFF_SUCCESS = "FINDBYDEPARTMENT_ID_STAFF_SUCCESS";
export const FINDBYDESIGNATION_ID_STAFF_SUCCESS = "FINDBYDESIGNATION_ID_STAFF_SUCCESS";
export const FINDBYGENDER_ID_STAFF_SUCCESS = "FINDBYGENDER_ID_STAFF_SUCCESS";
export const FINDBYROLE_ID_STAFF_SUCCESS = "FINDBYROLE_ID_STAFF_SUCCESS";
export const FINDBYSCHOOL_ID_STAFF_SUCCESS = "FINDBYSCHOOL_ID_STAFF_SUCCESS";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const LIST_STAFF_SUCCESS = "LIST_STAFF_SUCCESS";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const FINDBYACADEMIC_ID_USER_SUCCESS = "FINDBYACADEMIC_ID_USER_SUCCESS";
export const FINDBYROLE_ID_USER_SUCCESS = "FINDBYROLE_ID_USER_SUCCESS";
export const FINDBYSCHOOL_ID_USER_SUCCESS = "FINDBYSCHOOL_ID_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// ACADEMIC_YEAR
export const CREATE_ACADEMIC_YEAR_SUCCESS = "CREATE_ACADEMIC_YEAR_SUCCESS";
export const DELETE_ACADEMIC_YEAR_SUCCESS = "DELETE_ACADEMIC_YEAR_SUCCESS";
export const GET_ACADEMIC_YEAR_SUCCESS = "GET_ACADEMIC_YEAR_SUCCESS";
export const LIST_ACADEMIC_YEAR_SUCCESS = "LIST_ACADEMIC_YEAR_SUCCESS";
export const UPDATE_ACADEMIC_YEAR_SUCCESS = "UPDATE_ACADEMIC_YEAR_SUCCESS";

// BLOOD_GROUP
export const LIST_BLOOD_GROUP_SUCCESS = "LIST_BLOOD_GROUP_SUCCESS";

// CLASSSES
export const CREATE_CLASSSES_SUCCESS = "CREATE_CLASSSES_SUCCESS";
export const DELETE_CLASSSES_SUCCESS = "DELETE_CLASSSES_SUCCESS";
export const FINDBYSCHOOL_ID_CLASSSES_SUCCESS = "FINDBYSCHOOL_ID_CLASSSES_SUCCESS";
export const GET_CLASSSES_SUCCESS = "GET_CLASSSES_SUCCESS";
export const LIST_CLASSSES_SUCCESS = "LIST_CLASSSES_SUCCESS";
export const UPDATE_CLASSSES_SUCCESS = "UPDATE_CLASSSES_SUCCESS";

// GENDER
export const CREATE_GENDER_SUCCESS = "CREATE_GENDER_SUCCESS";
export const DELETE_GENDER_SUCCESS = "DELETE_GENDER_SUCCESS";
export const GET_GENDER_SUCCESS = "GET_GENDER_SUCCESS";
export const LIST_GENDER_SUCCESS = "LIST_GENDER_SUCCESS";
export const UPDATE_GENDER_SUCCESS = "UPDATE_GENDER_SUCCESS";

// RELIGION
export const LIST_RELIGION_SUCCESS = "LIST_RELIGION_SUCCESS";

// ROLES
export const CREATE_ROLES_SUCCESS = "CREATE_ROLES_SUCCESS";
export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const LIST_ROLES_SUCCESS = "LIST_ROLES_SUCCESS";
export const UPDATE_ROLES_SUCCESS = "UPDATE_ROLES_SUCCESS";

// SCHOOL
export const CREATE_SCHOOL_SUCCESS = "CREATE_SCHOOL_SUCCESS";
export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";
export const GET_SCHOOL_SUCCESS = "GET_SCHOOL_SUCCESS";
export const LIST_SCHOOL_SUCCESS = "LIST_SCHOOL_SUCCESS";
export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";

// SECTION
export const CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const FINDBYACADEMIC_ID_SECTION_SUCCESS = "FINDBYACADEMIC_ID_SECTION_SUCCESS";
export const FINDBYCLASSS_ID_SECTION_SUCCESS = "FINDBYCLASSS_ID_SECTION_SUCCESS";
export const FINDBYSCHOOL_ID_SECTION_SUCCESS = "FINDBYSCHOOL_ID_SECTION_SUCCESS";
export const GET_SECTION_SUCCESS = "GET_SECTION_SUCCESS";
export const LIST_SECTION_SUCCESS = "LIST_SECTION_SUCCESS";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";

// STUDENT
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const FINDBYACADEMIC_ID_STUDENT_SUCCESS = "FINDBYACADEMIC_ID_STUDENT_SUCCESS";
export const FINDBYCLASSS_ID_STUDENT_SUCCESS = "FINDBYCLASSS_ID_STUDENT_SUCCESS";
export const FINDBYGENDER_ID_STUDENT_SUCCESS = "FINDBYGENDER_ID_STUDENT_SUCCESS";
export const FINDBYROLE_ID_STUDENT_SUCCESS = "FINDBYROLE_ID_STUDENT_SUCCESS";
export const FINDBYSCHOOL_ID_STUDENT_SUCCESS = "FINDBYSCHOOL_ID_STUDENT_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const LIST_STUDENT_SUCCESS = "LIST_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
